name: Node CI

on:
- push
- pull_request

jobs:
  build:
    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm
      run: |
        npm i -g npm@^7.x
    - name: Install npm dependencies
      run: |
        npm ci
        node node_modules/puppeteer/install.js
      env:
        CI: true
    - name: lint code
      run: npm run lint
      env:
        CI: true
    - name: compile project
      run: npm run build
      env:
        CI: true
    - name: run unit tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm run test:unit
      env:
        CI: true
    - name: run smoke tests
      uses: coactions/setup-xvfb@v1
      with:
        run: npm run test:smoke
      env:
        CI: true
